- name: To print message
  hosts: web
  tasks: #lists of tasks/modules/collections
  - name: msg print
    ansible.builtin.debug:
     msg: " To print the message by using ansible module "

- name: To print message
  hosts: web
  tasks: #lists of tasks/modules/collections
  - name: msg print
    ansible.builtin.debug:
     msg: " To print the message by using ansible module play01 task02 "