- name: variables to  print
  hosts: web
  tasks: #lists/tasks/collections
  - name: print the message information
    ansible.buitin.debug:
     msg: "Hi started devops course it is completed by 4 months"
