- name: print information
  hosts: web
  vars:
    COURSE: "Devops"
    DURATION: "120+H"
    TRAINER: "Jakeer"
    TOPICS: #list
    - LINUX
    - AWS
    - SHELL
    - ANSIBLE
    - KUBERNETES
    - TERRAFORM
    live: true #boolean
    TOOLS: #map/dictonary
    -  ci: jenkins
    -  cm: ansible
    - cloud: aws
      aws:
      - s3
      - ec2
      - vpc
  tasks: #lists/modules/collections
  - name: print information
    ansible.builtin.debug:
      msg: "Hi we started {{COURSE}},duration is {{DURATION}}, trainer is {{TRAINER}},live is {{live}},tools are {{TOOLS}},topics are {{TOPICS}}"