- name: print information
  hosts:
  vars:
    COURSE: "Devops"
    DURATION: "120+H"
    TRAINER: "Jakeer"
    TOPICS: #list
    - LINUX
    - AWS
    - SHELL
    - ANSIBLE
    - KUBERNETES
    - TERRAFORM
    live: true #boolean
    tools: #map/dictonary
      ci: jenkins
      cm: ansible
      cloud: aws
  tasks: #lists/modules/collections
  - name: print information
    ansible.builtin.debug:
      msg: "Hi we started {{COURSE}},duration is {{DURATION}}, trainer is {{TRAINER}},live is {{live}},tools are {{tools}}"