- name: print facts
  hosts: web
  become: yes
  tasks: 
  - name: gathering facts
    ansible.builtin.debug:
      msg: " {{ ansible_facts }}"

  - name: install nginx Redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family "Redhat"

    - name: install nginx Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family "Debian"
