- name: print names
  hosts: web
  become: yes
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "print names are {{ item }} "
    loop:
    - Jakeer
    - chandra
    - rajesh
    - varun
    - ajith